"""add password column

Revision ID: f433dffec44c
Revises: 68f4f9170416
Create Date: 2026-05-10 18:49:30.838148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f433dffec44c'
down_revision: Union[str, Sequence[str], None] = '68f4f9170416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'user_table',
    sa.Column('password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user_table', ['email'])
    op.create_unique_constraint(None, 'user_table', ['username'])
    op.drop_column('user_table', 'hash_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_table', type_='unique')
    op.drop_constraint(None, 'user_table', type_='unique')
    op.drop_column('user_table', 'password')
    # ### end Alembic commands ###
